# Simple package

name: rbw
parent: default

matches:
    - triggers: [":rbw", ":bitwarden", ":bw"]
      replace: "{{password}}"
      vars:
          - name: password
            type: shell
            params:
                cmd: "sh $HOME/.local/share/espanso/packages/rbw/rbw-form.sh"

    - triggers: ["::rbw", "::bitwarden", "::bw"]
      replace: "{{password}}"
      vars:
          - name: password
            type: shell
            params:
                cmd: "sh $HOME/.local/share/espanso/packages/rbw/rbw-dmenu.sh"

